### PR TITLE
Fix legacy hashing warning

### PR DESCRIPTION
**Pull request by niil-ohlin**

### CODE REVIEW

**Comment by niil-ohlin** [comment]
This PR will fix your failing PR. I will be afk for a while so if you want you can merge it.

**Comment by mansbernhardt** [comment]
@niil-ohlin Sorry, I missed your PR. I did update my PR though and where I instead let the compiler automatically generate the hash function (as well as equatable).

**Comment by niil-ohlin** [comment]
awesome. That's even better.

**Comment by mansbernhardt** [comment]
@niil-ohlin Shouldn't we close this PR?

**Pull request closed without merging**
